var1 = input('Digite Algo: ')
print('O tipo primitivo desse valor é: {}!'.format(type(var1)))
print('Só tem espaços? {}!'.format(var1.isspace()))
print('É um número? {}!'.format(var1.isnumeric()))
print('É uma palavra? ', var1.isalpha())
print('É alfanumérico? ', var1.isalnum())
print('Está em maiúscula? ', var1.isupper())
print('Está em minúscula? ', var1.islower())
print('Está capitalizada? ', var1.istitle())
